spring:
  application:
    name: url-shortener

  datasource:
    url: jdbc:postgresql://${DB_HOST:dpg-d163rmp5pdvs73fq204g-a.singapore-postgres.render.com}/${DB_NAME:shorturl_vgzj}
    username: ${DB_USERNAME:bibek}
    password: ${DB_PASSWORD:XzSmpPLdr0KJ1Xt2U2LQ6SJgJWOKtvzb}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: ${SERVER_PORT:9091}
  servlet:
    context-path: /url-shortner
